# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  list-all-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: List all files
      run: ls
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ContactList.sln
    - name: Build
      run: dotnet build ContactList.sln --no-restore
    - name: Test
      run: dotnet test ContactList.sln --no-build --verbosity normal
